### ISSUE TITLE
[Scheduled Maintenance] Site down for Maintenance

### ISSUE THREAD

**Issue by simar0at** [acdh-oeaw/status#562]
**Update Kubernetes version**
We will update the Kubernetes version on our cluster on Thursday, 27. 06. 2024. All services will restart and there may be short service interruptions for each service.

**Comment by csae8092** [comment]
There is a presentation scheduled for emt-static at 5pm today. Any chance the update will be finished by that time? @simar0at

**Comment by simar0at** [comment]
Yes, we will finish before 5pm.
